# CMake generated Testfile for 
# Source directory: /home/manoj/gsoc/gdcm/Testing/Source/MediaStorageAndFileFormat/Cxx
# Build directory: /home/manoj/gsoc/gdcm-build/Testing/Source/MediaStorageAndFileFormat/Cxx
# 
# This file replicates the SUBDIRS() and ADD_TEST() commands from the source
# tree CMakeLists.txt file, skipping any SUBDIRS() or ADD_TEST() commands
# that are excluded by CMake control structures, i.e. IF() commands.
ADD_TEST(TestAnonymizer "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestAnonymizer")
ADD_TEST(TestIconImageFilter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestIconImageFilter")
ADD_TEST(TestIconImageGenerator "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestIconImageGenerator")
ADD_TEST(TestIconImageGenerator2 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestIconImageGenerator2")
ADD_TEST(TestParseXPATH "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestParseXPATH")
ADD_TEST(TestValidate "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestValidate")
ADD_TEST(TestAnonymizeEvent "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestAnonymizeEvent")
ADD_TEST(TestFileDerivation "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestFileDerivation")
ADD_TEST(TestSegmentedPaletteColorLookupTable "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestSegmentedPaletteColorLookupTable")
ADD_TEST(TestPNMCodec "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestPNMCodec")
ADD_TEST(TestSpacing "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestSpacing")
ADD_TEST(TestSerieHelper "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestSerieHelper")
ADD_TEST(TestFileExplicitFilter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestFileExplicitFilter")
ADD_TEST(TestImageFragmentSplitter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageFragmentSplitter")
ADD_TEST(TestTagPath "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestTagPath")
ADD_TEST(TestOrientation "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestOrientation")
ADD_TEST(TestIconImage "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestIconImage")
ADD_TEST(TestImageHelper "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageHelper")
ADD_TEST(TestImageToImageFilter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageToImageFilter")
ADD_TEST(TestImageChangeTransferSyntax1 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageChangeTransferSyntax1")
ADD_TEST(TestImageChangeTransferSyntax2 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageChangeTransferSyntax2")
ADD_TEST(TestImageChangeTransferSyntax3 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageChangeTransferSyntax3")
ADD_TEST(TestImageChangeTransferSyntax4 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageChangeTransferSyntax4")
ADD_TEST(TestImageChangeTransferSyntax6 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageChangeTransferSyntax6")
ADD_TEST(TestImageChangeTransferSyntax7 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageChangeTransferSyntax7")
ADD_TEST(TestImageApplyLookupTable "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageApplyLookupTable")
ADD_TEST(TestImageChangePlanarConfiguration "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageChangePlanarConfiguration")
ADD_TEST(TestCoder "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestCoder")
ADD_TEST(TestDecoder "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestDecoder")
ADD_TEST(TestRescaler "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestRescaler")
ADD_TEST(TestDumper "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestDumper")
ADD_TEST(TestDictPrinter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestDictPrinter")
ADD_TEST(TestApplicationEntity "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestApplicationEntity")
ADD_TEST(TestStringFilter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestStringFilter")
ADD_TEST(TestUIDGenerator "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestUIDGenerator")
ADD_TEST(TestPrinter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestPrinter")
ADD_TEST(TestPrint "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestPrint")
ADD_TEST(TestSorter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestSorter")
ADD_TEST(TestImageReader "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageReader")
ADD_TEST(TestStreamImageReader "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestStreamImageReader")
ADD_TEST(TestStreamImageWriter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestStreamImageWriter")
ADD_TEST(TestImageReaderRandomEmpty "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageReaderRandomEmpty")
ADD_TEST(TestDirectionCosines "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestDirectionCosines")
ADD_TEST(TestImageWriter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageWriter")
ADD_TEST(TestCodec "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestCodec")
ADD_TEST(TestPDFCodec "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestPDFCodec")
ADD_TEST(TestRLECodec "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestRLECodec")
ADD_TEST(TestAudioCodec "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestAudioCodec")
ADD_TEST(TestImage "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImage")
ADD_TEST(TestPhotometricInterpretation "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestPhotometricInterpretation")
ADD_TEST(TestLookupTable "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestLookupTable")
ADD_TEST(TestOverlay "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestOverlay")
ADD_TEST(TestCurve "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestCurve")
ADD_TEST(TestPixelFormat "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestPixelFormat")
ADD_TEST(TestPersonName "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestPersonName")
ADD_TEST(TestImageCodec "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageCodec")
ADD_TEST(TestImageConverter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageConverter")
ADD_TEST(TestJPEGCodec "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestJPEGCodec")
ADD_TEST(TestRAWCodec "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestRAWCodec")
ADD_TEST(TestDICOMDIR "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestDICOMDIR")
ADD_TEST(TestWaveform "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestWaveform")
ADD_TEST(TestFiducials "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestFiducials")
ADD_TEST(TestEncapsulatedDocument "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestEncapsulatedDocument")
ADD_TEST(TestSpectroscopy "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestSpectroscopy")
ADD_TEST(TestScanner "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestScanner")
ADD_TEST(TestPrinter2 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestPrinter2")
ADD_TEST(TestIPPSorter "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestIPPSorter")
ADD_TEST(TestIPPSorter2 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestIPPSorter2")
ADD_TEST(TestCopyDataSet "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestCopyDataSet")
ADD_TEST(TestDataElementValueAsSQ "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestDataElementValueAsSQ")
ADD_TEST(TestImageWriter2 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageWriter2")
ADD_TEST(TestDICOMDIRGenerator1 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestDICOMDIRGenerator1")
ADD_TEST(TestDICOMDIRGenerator2 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestDICOMDIRGenerator2")
SET_TESTS_PROPERTIES(TestDICOMDIRGenerator2 PROPERTIES  WILL_FAIL "ON")
ADD_TEST(TestImageChangeTransferSyntax5 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestImageChangeTransferSyntax5")
ADD_TEST(TestUIDGenerator2 "/home/manoj/gsoc/gdcm-build/bin/gdcmMSFFTests" "TestUIDGenerator2")
