# CMake generated Testfile for 
# Source directory: /home/manoj/gsoc/gdcm/Testing/Source/DataStructureAndEncodingDefinition/Cxx
# Build directory: /home/manoj/gsoc/gdcm-build/Testing/Source/DataStructureAndEncodingDefinition/Cxx
# 
# This file replicates the SUBDIRS() and ADD_TEST() commands from the source
# tree CMakeLists.txt file, skipping any SUBDIRS() or ADD_TEST() commands
# that are excluded by CMake control structures, i.e. IF() commands.
ADD_TEST(TestAttribute "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestAttribute")
ADD_TEST(TestCodeString "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestCodeString")
ADD_TEST(TestAttribute1 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestAttribute1")
ADD_TEST(TestAttribute7 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestAttribute7")
ADD_TEST(TestLO "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestLO")
ADD_TEST(TestCSAElement "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestCSAElement")
ADD_TEST(TestPreamble "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestPreamble")
ADD_TEST(TestReader "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestReader")
ADD_TEST(TestReaderUpToTag "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestReaderUpToTag")
ADD_TEST(TestReaderSelectedTags "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestReaderSelectedTags")
ADD_TEST(TestReaderCanRead "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestReaderCanRead")
ADD_TEST(TestWriter "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestWriter")
ADD_TEST(TestWriter2 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestWriter2")
ADD_TEST(TestCSAHeader "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestCSAHeader")
ADD_TEST(TestByteSwapFilter "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestByteSwapFilter")
ADD_TEST(TestBasicOffsetTable "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestBasicOffsetTable")
ADD_TEST(TestComposite "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestComposite")
ADD_TEST(TestDataElement "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestDataElement")
ADD_TEST(TestDataSet "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestDataSet")
ADD_TEST(TestVRDS "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestVRDS")
ADD_TEST(TestDS "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestDS")
ADD_TEST(TestVRLT "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestVRLT")
ADD_TEST(TestVRUI "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestVRUI")
ADD_TEST(TestElement "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestElement")
ADD_TEST(TestFileMetaInformation "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestFileMetaInformation")
ADD_TEST(TestFile "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestFile")
ADD_TEST(TestFileSet "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestFileSet")
ADD_TEST(TestFragment "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestFragment")
ADD_TEST(TestItem "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestItem")
ADD_TEST(TestSequenceOfFragments "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestSequenceOfFragments")
ADD_TEST(TestSequenceOfItems "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestSequenceOfItems")
ADD_TEST(TestTag "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestTag")
ADD_TEST(TestPrivateTag "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestPrivateTag")
ADD_TEST(TestTransferSyntax "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestTransferSyntax")
ADD_TEST(TestMediaStorage "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestMediaStorage")
ADD_TEST(TestVL "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestVL")
ADD_TEST(TestVM "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestVM")
ADD_TEST(TestVR "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestVR")
ADD_TEST(TestElement2 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestElement2")
ADD_TEST(TestElement4 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestElement4")
ADD_TEST(TestElement5 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestElement5")
ADD_TEST(TestReader2 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestReader2")
ADD_TEST(TestAttribute8 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestAttribute8")
ADD_TEST(TestPDBHeader "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestPDBHeader")
ADD_TEST(TestSequenceOfItems2 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestSequenceOfItems2")
ADD_TEST(TestReader3 "/home/manoj/gsoc/gdcm-build/bin/gdcmDSEDTests" "TestReader3")
